In [1]:
using LinearAlgebra
using PyPlot
using ForwardDiff
using MatrixCalculus

In [2]:
#Model parameters
g = 9.81 #m/s^2
m = 1.0 #kg 
ℓ = 0.3 #meters

#Thrust and gimbal limits
umin = [0.0; 0.0]
umax = [0.6*m*g; 0.6*m*g]

uhover = [0.5*m*g; 0.5*m*g]

h = 0.025 #time step (50 Hz)

0.025

In [3]:
#Planar Quadrotor Dynamics
function quad_dynamics(x,u)
    J = 0.2*m*ℓ*ℓ
    
    θ = x[3]
    
    ẍ = (1/m)*(u[1] + u[2])*sin(θ)
    ÿ = (1/m)*(u[1] + u[2])*cos(θ) - g
    θ̈ = (1/J)*(ℓ/2)*(u[2] - u[1])
    
    return [x[4:6]; ẍ; ÿ; θ̈]
end

quad_dynamics (generic function with 1 method)

In [4]:
function quad_dynamics_rk4(x,u)
    #RK4 integration with zero-order hold on u
    f1 = quad_dynamics(x, u)
    f2 = quad_dynamics(x + 0.5*h*f1, u)
    f3 = quad_dynamics(x + 0.5*h*f2, u)
    f4 = quad_dynamics(x + h*f3, u)
    return x + (h/6.0)*(f1 + 2*f2 + 2*f3 + f4)
end

quad_dynamics_rk4 (generic function with 1 method)

In [5]:
#First derivatives of dynamics
function dfdx(x,u)
    return ForwardDiff.jacobian(dx->quad_dynamics_rk4(dx,u),x)
end

function dfdu(x,u)
    return ForwardDiff.jacobian(du->quad_dynamics_rk4(x,du),u)
end

dfdu (generic function with 1 method)

In [6]:
#Second derivatives of dynamics
function dAdx(x,u)
    return ForwardDiff.jacobian(dx->vec(dfdx(dx,u)),x)
end

function dBdx(x,u)
    return ForwardDiff.jacobian(dx->vec(dfdu(dx,u)),x)
end

function dAdu(x,u)
    return ForwardDiff.jacobian(du->vec(dfdx(x,du)),u)
end

function dBdu(x,u)
    return ForwardDiff.jacobian(du->vec(dfdu(x,du)),u)
end

dBdu (generic function with 1 method)

In [7]:
Nx = 6     # number of state
Nu = 2     # number of controls
Tfinal = 1.5 # final time
Nt = Int(Tfinal/h)+1    # number of time steps
thist = Array(range(0,h*(Nt-1), step=h));

In [8]:
# Cost weights
Q = Diagonal([ones(3); 0.1*ones(3)]);
R = Array(.01*I(Nu));
Qn = Array(100.0*I(Nx));

In [9]:
#Reference trajectory for flip
x1ref = [LinRange(-3,0,20); zeros(20); LinRange(0,3,21)]
x2ref = [ones(20); LinRange(1,3,10); LinRange(3,1,10); ones(21)]
θref = [zeros(20); LinRange(0,-2*pi,20); -2*pi*ones(21)]
v1ref = [6.0*ones(20); zeros(20); 6.0*ones(21)]
v2ref = [zeros(20); 8.0*ones(10); -8.0*ones(10); zeros(21)]
ωref = [zeros(20); -4*pi*ones(20); zeros(21)]
xref = [x1ref'; x2ref'; θref'; v1ref'; v2ref'; ωref']

6×61 Array{Float64,2}:
 -3.0  -2.84211  -2.68421  -2.52632  …   2.7       2.85      3.0
  1.0   1.0       1.0       1.0          1.0       1.0       1.0
  0.0   0.0       0.0       0.0         -6.28319  -6.28319  -6.28319
  6.0   6.0       6.0       6.0          6.0       6.0       6.0
  0.0   0.0       0.0       0.0          0.0       0.0       0.0
  0.0   0.0       0.0       0.0      …   0.0       0.0       0.0

In [10]:
#Reference trajectory for straight line
x1ref = Array(LinRange(-2,2,101))
x2ref = Array(ones(101))
θref = Array(zeros(101))
v1ref = Array((4.0/3.0)*ones(101))
v2ref = Array(zeros(101))
ωref = Array(zeros(101))
xref = [x1ref'; x2ref'; θref'; v1ref'; v2ref'; ωref']

6×101 Array{Float64,2}:
 -2.0      -1.96     -1.92     …  1.88     1.92     1.96     2.0
  1.0       1.0       1.0         1.0      1.0      1.0      1.0
  0.0       0.0       0.0         0.0      0.0      0.0      0.0
  1.33333   1.33333   1.33333     1.33333  1.33333  1.33333  1.33333
  0.0       0.0       0.0         0.0      0.0      0.0      0.0
  0.0       0.0       0.0      …  0.0      0.0      0.0      0.0

In [11]:
function stage_cost(x,u,k)
    return 0.5*(x-xref[:,k])'*Q*(x-xref[:,k]) + 0.5*(u-uhover)'*R*(u-uhover)
    #return 0.5*(x-xgoal)'*Q*(x-xgoal) + 0.5*(u-uhover)'*R*(u-uhover)
end

stage_cost (generic function with 1 method)

In [12]:
function terminal_cost(x)
    return 0.5*(x-xref[:,Nt])'*Qn*(x-xref[:,Nt])
    #return 0.5*(x-xgoal)'*Qn*(x-xgoal)
end

terminal_cost (generic function with 1 method)

In [13]:
function cost(xtraj,utraj)
    J = 0
    for k = 1:(Nt-1)
        J += stage_cost(xtraj[:,k],utraj[:,k],k)
    end
    J += terminal_cost(xtraj[:,Nt])
    return J
end

cost (generic function with 1 method)

In [14]:
function V(x,k)
    Δx = x-xtraj[:,k]
    return 0.5*Δx'*P[:,:,k]*Δx + p[:,k]'*Δx
end

V (generic function with 1 method)

In [28]:
function S(x,u,k)
    return stage_cost(x,u,k) + V(quad_dynamics_rk4(x,u),k+1)
end

S (generic function with 2 methods)

In [65]:
#Initial guess trajectory (hover)
x0 = [-2.0; 1.0; 0; 0; 0; 0]
xgoal = [2.0; 1.0; 0; 0; 0; 0]
xtraj = kron(ones(1,Nt), x0)
utraj = kron(ones(1,Nt-1), uhover)
J = cost(xtraj,utraj)

438.3902222222222

In [66]:
#DDP Algorithm
p = zeros(Nx,Nt)
P = zeros(Nx,Nx,Nt)
j = ones(Nu,Nt-1)
K = zeros(Nu,Nx,Nt-1)
ΔJ = 0.0

Gxx = zeros(Nx,Nx)
Guu = zeros(Nu,Nu)
Gxu = zeros(Nx,Nu)
Gux = zeros(Nu,Nx)

iter = 0
while maximum(abs.(j[:])) > 1e-3
    iter += 1
    
    p = zeros(Nx,Nt)
    P = zeros(Nx,Nx,Nt)
    j = zeros(Nu,Nt-1)
    K = zeros(Nu,Nx,Nt-1)
    ΔJ = 0.0

    p[:,Nt] = ForwardDiff.gradient(terminal_cost,xtraj[:,Nt])
    P[:,:,Nt] = ForwardDiff.hessian(terminal_cost,xtraj[:,Nt])
    
    #Backward Pass
    for k = (Nt-1):-1:1
        #Calculate derivatives
        q = ForwardDiff.gradient(dx->stage_cost(dx,utraj[:,k],k),xtraj[:,k])
        Q = ForwardDiff.hessian(dx->stage_cost(dx,utraj[:,k],k),xtraj[:,k])
    
        r = ForwardDiff.gradient(du->stage_cost(xtraj[:,k],du,k),utraj[:,k])
        R = ForwardDiff.hessian(du->stage_cost(xtraj[:,k],du,k),utraj[:,k])
    
        A = dfdx(xtraj[:,k],utraj[:,k])
        B = dfdu(xtraj[:,k],utraj[:,k])
    
        Ax = dAdx(xtraj[:,k],utraj[:,k])
        Bx = dBdx(xtraj[:,k],utraj[:,k])
        Au = dAdu(xtraj[:,k],utraj[:,k])
        Bu = dBdu(xtraj[:,k],utraj[:,k])
    
        gx = q + A'*p[:,k+1]
        gu = r + B'*p[:,k+1]
    
        Gxx = Q + A'*P[:,:,k+1]*A + kron(p[:,k+1]',I(Nx))*comm(Nx,Nx)*Ax
        Guu = R + B'*P[:,:,k+1]*B + kron(p[:,k+1]',I(Nu))*comm(Nx,Nu)*Bu
        Gxu = A'*P[:,:,k+1]*B + kron(p[:,k+1]',I(Nx))*comm(Nx,Nx)*Au
        Gux = B'*P[:,:,k+1]*A + kron(p[:,k+1]',I(Nu))*comm(Nx,Nu)*Bx
    
        α = 1e-5
        Guu += α*I
        Gxx += α*I
        C = cholesky(Symmetric([Gxx Gxu; Gux Guu]), check=false)
        while !issuccess(C)
            α = 10.0*α
            Guu += α*I
            Gxx += α*I
            C = cholesky(Symmetric([Gxx Gxu; Gux Guu]), check=false)
        end
        display(α)
    
        j[:,k] .= Guu\gu
        K[:,:,k] .= Guu\Gux
    
        p[:,k] .= gx - K[:,:,k]'*gu + K[:,:,k]'*Guu*j[:,k] - Gxu*j[:,k]
        P[:,:,k] .= Gxx + K[:,:,k]'*Guu*K[:,:,k] - Gxu*K[:,:,k] - K[:,:,k]'*Gux
    
        ΔJ += gu'*j[:,k]
    end
    display(j)

    #Forward rollout with line search
    xn = zeros(Nx,Nt)
    un = zeros(Nu,Nt-1)
    xn[:,1] = xtraj[:,1]
    α = 1.0

    for k = 1:(Nt-1)
        un[:,k] .= utraj[:,k] - α*j[:,k] - K[:,:,k]*(xn[:,k]-xtraj[:,k])
        xn[:,k+1] .= quad_dynamics_rk4(xn[:,k],un[:,k])
    end
    Jn = cost(xn,un)
    
    while Jn > (J - 1e-2*α*ΔJ)
        α = 0.5*α
        for k = 1:(Nt-1)
            un[:,k] .= utraj[:,k] - α*j[:,k] - K[:,:,k]*(xn[:,k]-xtraj[:,k])
            xn[:,k+1] .= quad_dynamics_rk4(xn[:,k],un[:,k])
        end
        Jn = cost(xn,un)
    end
    display(α)
    
    J = Jn
    xtraj .= xn
    utraj .= un
end

1.0

1.0

1.0

1.0

10.0

1.0

10.0

1.0

10.0

1.0

1.0

10.0

1.0

1.0

1.0

10.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

1.0

0.1

1.0

1.0

1.0

1.0

1.0

0.1

1.0

1.0

0.1

1.0

2×60 Array{Float64,2}:
  0.790932   4.36137   1.08784   …   0.24928    0.0798484   0.00291441
 -0.439384  -1.18887  -0.691182     -0.248291  -0.080246   -0.00294191

1.0

1.0e-5

1.0e-5

0.1

0.1

1.0

0.1

0.1

1.0

0.1

1.0

0.1

1.0

0.1

1.0

1.0

0.1

1.0

0.1

1.0

1.0

0.1

1.0

0.1

1.0

1.0

0.1

1.0

1.0

0.1

1.0

1.0

0.1

1.0

1.0

0.1

1.0

1.0

0.1

1.0

0.1

1.0

0.1

1.0

0.1

1.0

0.1

0.1

1.0

0.1

0.1

0.1

0.1

0.1

1.0

0.1

0.1

0.1

0.1

0.1

0.1

2×60 Array{Float64,2}:
  2.50686    2.24898    2.41977   …   0.120435  -0.132755   0.341372
 -0.956138  -0.841005  -0.832067     -0.165424   0.0983972  0.357801

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.1

0.01

0.01

0.01

0.1

0.01

0.01

0.01

0.1

0.01

0.01

0.01

0.01

0.01

1.0e-5

0.01

0.001

0.01

1.0e-5

0.001

0.01

1.0e-5

0.0001

0.01

1.0e-5

0.01

0.01

0.001

0.01

0.01

0.01

0.1

0.01

0.01

0.1

0.1

0.01

0.1

2×60 Array{Float64,2}:
  0.918879   1.50924    0.573312  …  -0.213323  -1.36778  -0.728746
 -0.41894   -0.300473  -0.272999     -1.43203   -1.05885  -0.728393

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.1

0.01

0.1

0.01

2×60 Array{Float64,2}:
 1.87726   0.0346789  0.582809  …  0.104111  -0.0275497  -0.0484739
 0.170668  0.0415547  0.376755     0.237305   0.0832411  -0.0483815

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
 0.921262   -0.0854994  0.210405   -0.405534   …  -0.00128921  -0.00145317
 0.0608971   0.0861206  0.0607509   0.0335513      0.00096726  -0.00145139

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
 0.48024    -0.123029   0.0695718   -0.227138   …  -6.04548e-6  -2.36643e-7
 0.0184082   0.0980565  0.00147429  -0.0427324      8.45239e-6  -2.7728e-7

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.27182     -0.128075    0.0248837  -0.121374   …  -1.35256e-6  -3.51159e-7
 -0.00854785   0.0940984  -0.0108191  -0.0423984      7.17241e-7  -3.61312e-7

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.166529   -0.121185    0.0108653  -0.0624123  …  -4.35218e-7  -1.02886e-7
 -0.0237782   0.0846415  -0.0113301  -0.0293213      4.27404e-7  -1.07134e-7

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.110016   -0.110372    0.00635498  -0.0308228  …  -1.4062e-7   -4.33061e-8
 -0.0308572   0.0739445  -0.00937494  -0.0180097      1.81851e-7  -4.49266e-8

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.0778968  -0.0987871   0.00475543  -0.0143128  …  -3.31218e-8  -2.42014e-8
 -0.0328491   0.0636542  -0.00734253  -0.0104405      4.73272e-8  -2.46393e-8

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.0585374  -0.0876648   0.00403522  …   9.76033e-9  -1.60225e-8
 -0.0319612   0.0543485  -0.00571659     -1.78037e-8  -1.5929e-8

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.0461168  -0.0774588   0.003579    …   2.69646e-8  -1.17913e-8
 -0.0296194   0.0461688  -0.00449476     -4.6339e-8   -1.14699e-8

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.03762    -0.0682929   0.00320735  …   3.29562e-8  -9.33387e-9
 -0.0266768   0.039082   -0.00358227     -5.65734e-8  -8.92902e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.0314431  -0.0601509   0.00287254  …   3.38283e-8  -7.77674e-9
 -0.0236115   0.0329906  -0.00289076     -5.79604e-8  -7.35715e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.0267109  -0.0529603   0.00256448  …   3.23766e-8  -6.70881e-9
 -0.0206719   0.0277795  -0.00235545     -5.52772e-8  -6.30615e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.022933   -0.0466294   0.00228231  …   2.99473e-8  -5.92038e-9
 -0.0179735   0.023335   -0.00193217     -5.09116e-8  -5.54805e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.0198248  -0.0410642   0.00202631  …   2.72002e-8  -5.29999e-9
 -0.0155579   0.0195528  -0.00159135     -4.60388e-8  -4.96236e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.0172139  -0.0361756   0.00179611  …   2.44557e-8  -4.78676e-9
 -0.0134277   0.01634    -0.00131302     -4.122e-8    -4.48385e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.0149903  -0.0318823   0.00159048  …   2.18619e-8  -4.34651e-9
 -0.0115664   0.0136152  -0.00108342     -3.67061e-8  -4.07635e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.0130794   -0.0281116   0.00140766   …   1.94799e-8  -3.95943e-9
 -0.00994966   0.0113079  -0.000892722     -3.25926e-8  -3.71926e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.0114277  -0.024799    0.00124564   …   1.73266e-8  -3.61359e-9
 -0.0085504   0.0093572  -0.000733662     -2.88992e-8  -3.40044e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00999468  -0.021888     0.00110233   …   1.53974e-8  -3.30142e-9
 -0.00734227   0.00771074  -0.000600694     -2.56097e-8  -3.11239e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00874833  -0.0193287    0.000975735  …   1.36777e-8  -3.01784e-9
 -0.00630083   0.00632352  -0.000489452     -2.26928e-8  -2.85024e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00766251  -0.0170777   0.000863963  …   1.21493e-8  -2.7592e-9
 -0.00540405   0.005157   -0.000396414     -2.01124e-8  -2.61059e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00671543  -0.0150968    0.000765304  …   1.07931e-8  -2.52275e-9
 -0.00463245   0.00417814  -0.000318689     -1.78319e-8  -2.39094e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00588863  -0.0133529   0.000678218  …   9.59066e-9  -2.30628e-9
 -0.00396894   0.0033587  -0.000253874     -1.58174e-8  -2.18933e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00516634  -0.0118167    0.00060133   …   8.525e-9    -2.10795e-9
 -0.00339868   0.00267451  -0.000199954     -1.40376e-8  -2.00413e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00453496  -0.0104628    0.000533424  …   7.58058e-9  -1.92617e-9
 -0.00290877   0.00210492  -0.000155229     -1.24647e-8  -1.83397e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00398277  -0.00926906   0.000473426  …   6.7435e-9   -1.75954e-9
 -0.00248805   0.0016323   -0.000118262     -1.10741e-8  -1.67763e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00349959  -0.00821585   0.000420392  …   6.00139e-9  -1.60683e-9
 -0.0021269    0.00124163  -8.78328e-5      -9.84394e-9  -1.53401e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00307659  -0.00728617    0.00037349  …   5.34324e-9  -1.46688e-9
 -0.001817     0.000920086  -6.29052e-5     -8.7552e-9   -1.40212e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.0027061   -0.00646511    0.00033199  …   4.75936e-9  -1.33869e-9
 -0.00155119   0.000656747  -4.26005e-5     -7.79102e-9  -1.28105e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00238145  -0.00573957    0.000295251  …   4.24114e-9  -1.22129e-9
 -0.0013233    0.000442328  -2.61722e-5      -6.93667e-9  -1.16997e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00209684  -0.0050981     0.000262709  …   3.78101e-9  -1.11382e-9
 -0.001128     0.000268934  -1.29869e-5      -6.17918e-9  -1.06811e-9

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00184721   -0.00453066    0.000233871  …   3.37229e-9  -1.01548e-9
 -0.000960703   0.000129861  -2.50783e-6      -5.50719e-9  -9.74746e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00162815   -0.00402843  0.0002083   …   3.00905e-9  -9.25529e-10
 -0.000817475   1.94231e-5  5.71977e-6     -4.9107e-9   -8.89212e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00143584   -0.00358368  0.000185615  …   2.6861e-9   -8.43291e-10
 -0.000694915  -6.71954e-5  1.20805e-5      -4.38093e-9  -8.10894e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00126691   -0.00318962   0.000165479  …   2.39884e-9  -7.68131e-10
 -0.000590099  -0.000134068  1.68991e-5      -3.91017e-9  -7.39221e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.00111845   -0.00284029   0.000147597  …   2.14319e-9  -6.99469e-10
 -0.000500514  -0.000184636  2.04495e-5      -3.4916e-9   -6.73656e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.000987921  -0.00253045  0.000131708  …   1.91558e-9  -6.3677e-10
 -0.000423996  -0.0002218   2.29623e-5      -3.11925e-9  -6.13714e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.000873092  -0.00225549   0.000117582  …   1.71285e-9  -5.79536e-10
 -0.000358683  -0.000248002  2.46312e-5      -2.78783e-9  -5.58931e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.000772025  -0.00201135   0.000105018  …   1.53218e-9  -5.27313e-10
 -0.000302978  -0.000265294  2.56186e-5      -2.4927e-9   -5.08892e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.000683025  -0.00179447   9.38376e-5  …   1.37111e-9  -4.79678e-10
 -0.000255503  -0.000275393  2.60602e-5     -2.22975e-9  -4.63203e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.000604609  -0.0016017    8.3883e-5   …   1.22744e-9  -4.36244e-10
 -0.000215079  -0.000279737  2.60693e-5     -1.99535e-9  -4.21502e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.000535482  -0.00143028   7.50157e-5  …   1.09923e-9  -3.96654e-10
 -0.000180691  -0.000279525  2.57401e-5     -1.7863e-9   -3.83461e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.000474513  -0.00127776   6.71131e-5  …   9.84786e-10  -3.6058e-10
 -0.000151465  -0.000275752  2.51506e-5     -1.59977e-9   -3.48764e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.000420709  -0.001142     6.00669e-5  …   8.82568e-10  -3.27719e-10
 -0.000126655  -0.000269244  2.43649e-5     -1.43327e-9   -3.17136e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.000373203  -0.00102109   5.37813e-5  …   7.91238e-10  -2.97794e-10
 -0.000105618  -0.000260679  2.34362e-5     -1.28456e-9   -2.8831e-10

1.0

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

1.0e-5

0.01

0.01

0.01

0.1

0.01

2×60 Array{Float64,2}:
  0.000331235  -0.000913359  4.81718e-5  …   7.09603e-10  -2.70552e-10
 -8.78035e-5   -0.000250618  2.24074e-5     -1.1517e-9    -2.62051e-10

1.0

In [67]:
iter

49

In [70]:
Gxu-Gux'

6×2 Array{Float64,2}:
  1.66533e-16  -1.38778e-16
 -4.16334e-17   8.32667e-17
  1.11022e-16  -1.11022e-16
  1.94289e-16  -1.249e-16
 -1.38778e-17   1.38778e-17
  2.77556e-17  -1.38778e-17

In [69]:
Gux

2×6 Array{Float64,2}:
 -0.258232  0.114763  -0.751685  -0.19968   0.0876582  -0.127901
  0.146609  0.137829   0.2624     0.109147  0.0691974   0.119933

In [24]:
ForwardDiff.gradient(dx->V(dx,Nt-1),xtraj[:,Nt-1])-p[:,Nt-1]

6-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [25]:
ForwardDiff.hessian(dx->V(dx,Nt-1),xtraj[:,Nt-1])-P[:,:,Nt-1]

6×6 Array{Float64,2}:
  0.0           2.1684e-19    0.0          …  -2.77556e-17   8.23994e-18
 -1.0842e-19    0.0          -6.93889e-18      8.88178e-16  -5.4183e-16
  0.0           6.93889e-18   0.0              4.44089e-16  -2.22045e-16
  0.0           0.0           0.0             -4.44089e-15   4.16334e-16
  2.77556e-17  -1.11022e-15  -6.66134e-16      0.0           5.2236e-14
 -8.0231e-18    5.41844e-16   2.22045e-16  …  -5.22377e-14   0.0

In [29]:
ForwardDiff.gradient(dx->S(dx,utraj[:,Nt-1],Nt-1),xtraj[:,Nt-1])

6-element Array{Float64,1}:
 -5.300820426138337
  0.07447901297561565
 -4.921262341820255
  3.0558832009399066
  0.22824303306856958
  0.07850793537444656

In [30]:
q = ForwardDiff.gradient(x->stage_cost(x,utraj[:,Nt-1],Nt-1),xtraj[:,Nt-1])
A = dfdx(xtraj[:,Nt-1],utraj[:,Nt-1])
q + A'*p[:,Nt]

6-element Array{Float64,1}:
 -5.300820426138337
  0.07447901297561565
 -4.921262341820254
  3.0558832009399066
  0.22824303306856958
  0.07850793537444656

In [37]:
ForwardDiff.hessian(dx->S(dx,utraj[:,Nt-1],Nt-1),xtraj[:,Nt-1]) - (Q + A'*P[:,:,Nt]*A + kron(p[:,Nt]',I(Nx))*comm(Nx,Nx)*Ax)

6×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [ ]:
#Set up visualization
using MeshCat
using RobotZoo: Quadrotor, PlanarQuadrotor
using CoordinateTransformations, Rotations, Colors, StaticArrays, RobotDynamics

function set_mesh!(vis, model::L;
        scaling=1.0, color=colorant"black"
    ) where {L <: Union{Quadrotor, PlanarQuadrotor}} 
    # urdf_folder = joinpath(@__DIR__, "..", "data", "meshes")
    urdf_folder = @__DIR__
    # if scaling != 1.0
    #     quad_scaling = 0.085 * scaling
    obj = joinpath(urdf_folder, "quadrotor_scaled.obj")
    if scaling != 1.0
        error("Scaling not implemented after switching to MeshCat 0.12")
    end
    robot_obj = MeshFileGeometry(obj)
    mat = MeshPhongMaterial(color=color)
    setobject!(vis["robot"]["geom"], robot_obj, mat)
    if hasfield(L, :ned)
        model.ned && settransform!(vis["robot"]["geom"], LinearMap(RotX(pi)))
    end
end

function visualize!(vis, model::PlanarQuadrotor, x::StaticVector)
    py,pz = x[1], x[2]
    θ = x[3]
    settransform!(vis["robot"], compose(Translation(0,py,pz), LinearMap(RotX(-θ))))
end

function visualize!(vis, model, tf::Real, X)
    fps = Int(round((length(X)-1)/tf))
    anim = MeshCat.Animation(fps)
    n = state_dim(model)
    for (k,x) in enumerate(X)
        atframe(anim, k) do
            x = X[k]
            visualize!(vis, model, SVector{n}(x)) 
        end
    end
    setanimation!(vis, anim)
end

In [ ]:
vis = Visualizer()
model = PlanarQuadrotor()
set_mesh!(vis, model)
render(vis)

In [ ]:
X1 = [SVector{6}(x) for x in eachcol(xtraj)];
visualize!(vis, model, thist[end], X1)